on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .
  meta:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./utils/meta.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
