on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .
  update:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: for input in user/*.user.js; do sed "/==UserScript==/,/==\/UserScript==/!d" $input > meta/$(echo $input | cut -c 6- | sed 's/user\.js/meta\.js/'); done
      - run: sed -i "3s/.*/Copyright (c) $(sed -n "s/\/\/ @copyright\s*\(.*\),.*/\1/p" user/*user.js | sort -u | sed -z "s/\n/, /g;s/, $//") TheLastZombie/" LICENSE
      - uses: stefanzweifel/git-auto-commit-action@v4
